sudo: false
notifications:
  email:
    on_success: change
    on_failure: always

language: go
go:
  - tip
  - "1.10"
  - 1.9
  - 1.8
  - 1.7

script:
  - ./.travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
