sudo: false
notifications:
  email:
    on_success: change
    on_failure: always

language: go
go:
  - tip
  - "1.11"
  - "1.10"
  - 1.9
  # Prior to go 1.9 will not work due to github.com/miekg/dns dependency

script:
  - ./.travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
